ALTER TABLE user_attributes
  ADD COLUMN IF NOT EXISTS hair_type TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS skin_concerns TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS age_group TEXT NOT NULL DEFAULT '';
